// OKF MCP server — generated by mcpify. Do not hand-edit.
//
// `okf-mcp`'s own entry-point wiring — not declared in `lib.rs`,
// since no other `[[bin]]` target needs it (see `lib.rs`'s own doc comment).

pub mod compile;
pub mod config;
pub mod delete;
pub mod ingest;
pub mod lint;
pub mod rebuild;
pub mod reindex;
pub mod run;
pub mod search;
pub mod setup;
pub mod setup_wizard;
pub mod test_connection;
pub mod vault;
pub mod version;
