// OKF MCP server — generated by mcpify. Do not hand-edit.

use std::path::{Path, PathBuf};

use serde_json::{Map, Value};

use super::config_schema::Config;
use super::credential_storage::resolve_home_dir;
use super::errors::McpifyError;

const ENV_PREFIX: &str = "OKF_MCP";
const CONFIG_DIR_NAME: &str = ".okf-mcp";
const LOCAL_CONFIG_FILE: &str = "okf-mcp.config.yml";

/// Shares `credential_storage::resolve_home_dir`'s cross-platform lookup
/// (`HOME`, falling back to `USERPROFILE` on Windows, falling back to `.`)
/// rather than reading `HOME` directly, so config-file resolution doesn't
/// silently collapse to the current directory on Windows.
fn home_dir() -> PathBuf {
    resolve_home_dir()
}

/// The global config file path `load_config`'s cascade reads —
/// `~/.okf-mcp/config.yml`. Exposed for `cli::config`'s layered display.
pub fn global_config_path() -> PathBuf {
    home_dir().join(CONFIG_DIR_NAME).join("config.yml")
}

/// The local config file path `load_config`'s cascade reads —
/// `./okf-mcp.config.yml`. Exposed for `cli::config`'s layered display.
pub fn local_config_path() -> PathBuf {
    PathBuf::from(LOCAL_CONFIG_FILE)
}

/// Empty (not an error) when `path` doesn't exist or isn't a YAML object —
/// `load_config`'s cascade already treats "file absent" as "this layer
/// contributes nothing," and `cli::config`'s display wants the same
/// leniency. Exposed for that display to read a layer's raw contents.
pub fn read_yaml_if_exists(path: &Path) -> Map<String, Value> {
    let Ok(contents) = std::fs::read_to_string(path) else {
        return Map::new();
    };
    match serde_yaml::from_str::<Value>(&contents) {
        Ok(Value::Object(map)) => map,
        _ => Map::new(),
    }
}

fn parse_env_value(config_key: &str, value: &str) -> Value {
    if matches!(
        config_key,
        "rate_limit" | "timeout_ms" | "cache_size" | "retry_attempts" | "port"
    ) && let Ok(number) = value.parse::<u64>()
    {
        return Value::Number(number.into());
    }
    Value::String(value.to_string())
}

/// Every `OKF_MCP_*` env var actually set in this process, keyed by the
/// `Config` field it maps to. Exposed for `cli::config`'s layered display,
/// which needs exactly this — "which env vars are actually set" — not
/// just the fully-merged/defaulted result `load_config` returns.
///
/// No entry exists for `auth_method`: `AuthMethod` has exactly one variant
/// (`Pat`), which `Config`'s own serde default already resolves to — there
/// is nothing an env var could meaningfully override, so none is read.
pub fn env_overrides() -> Map<String, Value> {
    let mut overrides = Map::new();
    for (config_key, env_suffix) in [
        ("url", "URL"),
        ("firecrawl_base_url", "FIRECRAWL_API_URL"),
        ("api_version", "API_VERSION"),
        ("log_level", "LOG_LEVEL"),
        ("transport", "TRANSPORT"),
        ("host", "HOST"),
        ("cors_allow", "CORS_ALLOW"),
        ("rate_limit", "RATE_LIMIT"),
        ("timeout_ms", "TIMEOUT_MS"),
        ("cache_size", "CACHE_SIZE"),
        ("retry_attempts", "RETRY_ATTEMPTS"),
        ("port", "PORT"),
    ] {
        if let Ok(value) = std::env::var(format!("{ENV_PREFIX}_{env_suffix}")) {
            overrides.insert(config_key.to_string(), parse_env_value(config_key, &value));
        }
    }
    overrides.extend(custom_provider_env_overrides());
    overrides
}

const CUSTOM_PROVIDER_ENV_PREFIX: &str = "OKF_MCP_CUSTOM_PROVIDER_";
const CUSTOM_PROVIDER_ENV_SUFFIX: &str = "_BASE_URL";

/// Env var name for a named custom LLM provider's base URL, e.g.
/// `OKF_MCP_CUSTOM_PROVIDER_MYVLLM_BASE_URL` for a provider named
/// `"myvllm"` — the single source of truth for this format, shared by
/// `setup_wizard.rs`'s writer and `custom_provider_env_overrides`'s reader
/// below so they can never drift.
pub fn custom_provider_base_url_env_name(name: &str) -> String {
    let sanitized: String = name
        .to_uppercase()
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect();
    format!("{CUSTOM_PROVIDER_ENV_PREFIX}{sanitized}{CUSTOM_PROVIDER_ENV_SUFFIX}")
}

/// `OKF_MCP_CUSTOM_PROVIDER_<NAME>_BASE_URL` env vars, written by
/// `okf-mcp setup` when a custom provider's name+endpoint is persisted via
/// `.env` — folded into `env_overrides()`'s result under the
/// `custom_providers` key. Unlike the fixed fields above, provider names
/// are open-ended, so this scans `std::env::vars()` for the shared
/// prefix/suffix instead of a static list. The recovered name is
/// lowercased and underscores become hyphens (best-effort reverse of
/// `custom_provider_base_url_env_name`'s sanitization) — provider names
/// intended to round-trip losslessly through `.env` should stick to
/// lowercase alphanumerics/hyphens.
fn custom_provider_env_overrides() -> Map<String, Value> {
    let mut providers = Map::new();
    for (key, value) in std::env::vars() {
        if let Some(middle) = key
            .strip_prefix(CUSTOM_PROVIDER_ENV_PREFIX)
            .and_then(|rest| rest.strip_suffix(CUSTOM_PROVIDER_ENV_SUFFIX))
            && !middle.is_empty()
        {
            let name = middle.to_lowercase().replace('_', "-");
            providers.insert(name, serde_json::json!({ "base_url": value }));
        }
    }
    let mut overrides = Map::new();
    if !providers.is_empty() {
        overrides.insert("custom_providers".to_string(), Value::Object(providers));
    }
    overrides
}

/// Resolves configuration through the strict, stop-at-first-match cascade
/// (REQ-2.2): CLI flags -> env vars -> local file
/// (`./okf-mcp.config.yml`) -> home file
/// (`~/.okf-mcp/config.yml`) -> system file
/// (`/etc/okf-mcp/config.yml`) -> install-dir file -> built-in
/// defaults (applied by `Config`'s own `#[serde(default = ...)]` fields).
pub fn load_config(cli_flags: Map<String, Value>) -> Result<Config, McpifyError> {
    let install_dir = std::env::current_exe()
        .ok()
        .and_then(|exe| exe.parent().map(Path::to_path_buf))
        .unwrap_or_else(|| PathBuf::from("."));

    let layers = [
        cli_flags,
        env_overrides(),
        read_yaml_if_exists(&PathBuf::from(LOCAL_CONFIG_FILE)),
        read_yaml_if_exists(&home_dir().join(CONFIG_DIR_NAME).join("config.yml")),
        read_yaml_if_exists(&PathBuf::from("/etc/okf-mcp/config.yml")),
        read_yaml_if_exists(&install_dir.join("config.yml")),
    ];

    // Lowest-priority layer merged first, each higher-priority layer merged
    // on top — `cli_flags` (index 0 above, applied last here) always wins,
    // matching the cascade's stop-at-first-match ordering.
    let mut merged = Map::new();
    for layer in layers.into_iter().rev() {
        merged.extend(layer);
    }

    serde_json::from_value(Value::Object(merged))
        .map_err(|err| McpifyError::Configuration(format!("invalid configuration: {err}")))
}

#[cfg(test)]
mod tests {
    use super::super::config_schema::AuthMethod;
    use super::*;
    use serde_json::json;

    fn base_flags() -> Map<String, Value> {
        json!({ "url": "https://api.example.com", "auth_method": "pat" })
            .as_object()
            .unwrap()
            .clone()
    }

    #[test]
    fn applies_built_in_defaults_when_nothing_else_is_set() {
        let config = load_config(base_flags()).unwrap();
        assert_eq!(config.log_level, "info");
        assert_eq!(config.rate_limit, 100);
        assert_eq!(config.port, 3000);
    }

    #[test]
    fn cli_flags_win_over_everything_else() {
        let mut flags = base_flags();
        flags.insert("log_level".to_string(), json!("debug"));
        let config = load_config(flags).unwrap();
        assert_eq!(config.log_level, "debug");
    }

    /// `url`/`auth_method` used to be required — they're both defaulted now
    /// (`url` to empty, `auth_method` to its only variant) so a fresh
    /// `okf-mcp ingest` run isn't blocked on configuring fields it never
    /// reads. Every `Config` field is defaultable, so an entirely empty
    /// cascade now loads successfully instead of erroring.
    #[test]
    fn an_entirely_empty_cascade_loads_successfully_with_defaults() {
        // Serialized with `credential_storage`'s HOME-mutating tests —
        // see that lock's doc comment for why this matters.
        let _guard = crate::core::credential_storage::HOME_ENV_TEST_LOCK
            .lock()
            .unwrap_or_else(|e| e.into_inner());
        let temp_dir = tempfile::tempdir().unwrap();
        let prev_home = std::env::var_os("HOME");
        unsafe {
            std::env::set_var("HOME", temp_dir.path());
        }
        let config = load_config(Map::new());
        if let Some(prev) = prev_home {
            unsafe {
                std::env::set_var("HOME", prev);
            }
        } else {
            unsafe {
                std::env::remove_var("HOME");
            }
        }
        let config = config.unwrap();
        assert_eq!(config.url, "");
        assert_eq!(config.firecrawl_base_url, "https://api.firecrawl.dev");
        assert_eq!(config.auth_method, AuthMethod::Pat);
    }

    #[test]
    fn read_yaml_if_exists_parses_a_valid_yaml_object() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("config.yml");
        std::fs::write(&path, "log_level: debug\n").unwrap();
        let map = read_yaml_if_exists(&path);
        assert_eq!(map.get("log_level"), Some(&json!("debug")));
    }

    #[test]
    fn read_yaml_if_exists_ignores_non_object_yaml() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("config.yml");
        std::fs::write(&path, "- just\n- a\n- list\n").unwrap();
        assert!(read_yaml_if_exists(&path).is_empty());
    }

    #[test]
    fn env_overrides_reads_the_canonical_firecrawl_url_env_var_and_has_no_auth_method_entry() {
        // Serialized against every other test in this crate that calls
        // `load_config`/`env_overrides` and asserts a specific value — env
        // vars are process-global, so an unguarded mutation here could
        // race with e.g. `an_entirely_empty_cascade_loads_successfully_with_defaults`.
        let _guard = crate::core::credential_storage::HOME_ENV_TEST_LOCK
            .lock()
            .unwrap_or_else(|e| e.into_inner());
        // SAFETY: test-only env mutation, serialized by the guard above.
        unsafe {
            std::env::set_var(
                "OKF_MCP_FIRECRAWL_API_URL",
                "https://cfgmgrtest2.example/v1",
            );
        }
        let overrides = env_overrides();
        assert_eq!(
            overrides.get("firecrawl_base_url"),
            Some(&json!("https://cfgmgrtest2.example/v1"))
        );
        // No entry for auth_method at all — AuthMethod has exactly one
        // variant, so no env var is read for it anymore.
        assert!(!overrides.contains_key("auth_method"));
        // SAFETY: same guard as above.
        unsafe {
            std::env::remove_var("OKF_MCP_FIRECRAWL_API_URL");
        }
    }

    #[test]
    fn custom_provider_base_url_env_name_sanitizes_non_alphanumeric_characters() {
        assert_eq!(
            custom_provider_base_url_env_name("myvllm"),
            "OKF_MCP_CUSTOM_PROVIDER_MYVLLM_BASE_URL"
        );
        assert_eq!(
            custom_provider_base_url_env_name("my-vllm"),
            "OKF_MCP_CUSTOM_PROVIDER_MY_VLLM_BASE_URL"
        );
    }

    #[test]
    fn custom_provider_env_overrides_parses_matching_vars_and_ignores_unrelated_ones() {
        let _guard = crate::core::credential_storage::HOME_ENV_TEST_LOCK
            .lock()
            .unwrap_or_else(|e| e.into_inner());
        // SAFETY: test-only, uniquely-named env vars scoped to this test.
        unsafe {
            std::env::set_var(
                "OKF_MCP_CUSTOM_PROVIDER_CFGMGRTEST_BASE_URL",
                "https://cfgmgrtest.example/v1",
            );
            std::env::set_var("OKF_MCP_LOG_LEVEL", "debug");
        }

        let overrides = custom_provider_env_overrides();
        let providers = overrides
            .get("custom_providers")
            .and_then(|v| v.as_object())
            .unwrap();
        assert_eq!(
            providers.get("cfgmgrtest"),
            Some(&json!({ "base_url": "https://cfgmgrtest.example/v1" }))
        );
        assert!(!providers.contains_key("log_level"));

        // SAFETY: same guard as above.
        unsafe {
            std::env::remove_var("OKF_MCP_CUSTOM_PROVIDER_CFGMGRTEST_BASE_URL");
            std::env::remove_var("OKF_MCP_LOG_LEVEL");
        }
    }

    #[test]
    fn custom_provider_env_overrides_has_no_entry_for_an_unconfigured_provider() {
        let overrides = custom_provider_env_overrides();
        let providers = overrides
            .get("custom_providers")
            .and_then(|v| v.as_object());
        if let Some(providers) = providers {
            assert!(!providers.contains_key("never-configured-test-provider-xyz"));
        }
    }

    #[test]
    fn numeric_environment_overrides_are_typed_before_deserialization() {
        assert_eq!(parse_env_value("port", "33017"), json!(33017));
        assert_eq!(parse_env_value("timeout_ms", "2500"), json!(2500));
        assert_eq!(
            parse_env_value("url", "https://api.example"),
            json!("https://api.example")
        );
        assert_eq!(
            parse_env_value("port", "not-a-number"),
            json!("not-a-number")
        );
    }
}
