// OKF MCP server — generated by mcpify. Do not hand-edit.

use std::collections::HashMap;

use serde::{Deserialize, Serialize};

/// One variant per auth scheme mcpify discovered in the OpenAPI spec's
/// `components.securitySchemes` (or the interactive fallback) — REQ-1.2.1-3.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum AuthMethod {
    #[serde(rename = "pat")]
    Pat,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Transport {
    Stdio,
    Http,
}

fn default_log_level() -> String {
    "info".to_string()
}
fn default_rate_limit() -> u32 {
    100
}
fn default_timeout_ms() -> u64 {
    30_000
}
fn default_cache_size() -> u32 {
    500
}
fn default_retry_attempts() -> u32 {
    3
}
fn default_transport() -> Transport {
    Transport::Stdio
}
fn default_host() -> String {
    "127.0.0.1".to_string()
}
fn default_port() -> u16 {
    3000
}
fn default_firecrawl_base_url() -> String {
    "https://api.firecrawl.dev".to_string()
}
fn default_auth_method() -> AuthMethod {
    // The only variant that exists — defaulting it is unambiguous, and lets
    // config-cascade consumers that only care about Firecrawl (e.g. `okf-mcp
    // ingest`) skip specifying it at all.
    AuthMethod::Pat
}

// mcpify:versions:begin
fn default_api_version() -> String {
    "default".to_string()
}
// mcpify:versions:end

/// Persisted name + endpoint for a user-defined custom LLM provider,
/// written by `okf-mcp setup`'s persistence choice — never the API key,
/// which always lives in the OS keychain under `"llm-<name>"`.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CustomProviderEntry {
    pub base_url: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Config {
    /// Legacy any-operation-proxy target URL — belongs to code slated for
    /// removal (see `firecrawl_base_url` below for the field ingest/compile
    /// actually use). Defaulted to empty rather than required, so a fresh
    /// `okf-mcp ingest` run doesn't need to configure a field it never
    /// reads.
    #[serde(default)]
    pub url: String,
    /// Base URL of Firecrawl's own API — distinct from `url` above.
    /// `ingest::web`'s `scrape_url` reads this one. Defaults to Firecrawl's
    /// real cloud endpoint so a deployment only needs to set an API key to
    /// start ingesting, not also discover and configure the URL.
    #[serde(default = "default_firecrawl_base_url")]
    pub firecrawl_base_url: String,
    #[serde(default = "default_auth_method")]
    pub auth_method: AuthMethod,
    /// v8 multi-version support: an opaque label (not a compile-time enum
    /// like `AuthMethod` — version labels are arbitrary operator-supplied
    /// strings such as `"10.2.14"`, which can't cleanly become Rust
    /// identifiers), validated at runtime against the known version list
    /// in `data::store::resolve_store_path`/`validation::validator`.
    #[serde(default = "default_api_version")]
    pub api_version: String,
    #[serde(default = "default_log_level")]
    pub log_level: String,
    #[serde(default = "default_rate_limit")]
    pub rate_limit: u32,
    #[serde(default = "default_timeout_ms")]
    pub timeout_ms: u64,
    #[serde(default = "default_cache_size")]
    pub cache_size: u32,
    #[serde(default = "default_retry_attempts")]
    pub retry_attempts: u32,
    #[serde(default = "default_transport")]
    pub transport: Transport,
    #[serde(default = "default_host")]
    pub host: String,
    #[serde(default = "default_port")]
    pub port: u16,
    #[serde(default)]
    pub cors_allow: Option<String>,
    /// Named custom LLM providers configured via `okf-mcp setup` — keyed by
    /// the provider name used as `<name>` in `--model <name>/<model>`.
    #[serde(default)]
    pub custom_providers: HashMap<String, CustomProviderEntry>,
}
