// OKF MCP server — generated by mcpify. Do not hand-edit.

use std::path::{Path, PathBuf};

use serde_json::{Map, Value};

use super::config_schema::Config;
use super::credential_storage::resolve_home_dir;
use super::errors::McpifyError;

const ENV_PREFIX: &str = "OKF_MCP";
const CONFIG_DIR_NAME: &str = ".okf-mcp";
const LOCAL_CONFIG_FILE: &str = "okf-mcp.config.yml";

/// Shares `credential_storage::resolve_home_dir`'s cross-platform lookup
/// (`HOME`, falling back to `USERPROFILE` on Windows, falling back to `.`)
/// rather than reading `HOME` directly, so config-file resolution doesn't
/// silently collapse to the current directory on Windows.
fn home_dir() -> PathBuf {
    resolve_home_dir()
}

/// The global config file path `load_config`'s cascade reads —
/// `~/.okf-mcp/config.yml`. Exposed for `cli::config`'s layered display.
pub fn global_config_path() -> PathBuf {
    home_dir().join(CONFIG_DIR_NAME).join("config.yml")
}

/// The local config file path `load_config`'s cascade reads —
/// `./okf-mcp.config.yml`. Exposed for `cli::config`'s layered display.
pub fn local_config_path() -> PathBuf {
    PathBuf::from(LOCAL_CONFIG_FILE)
}

/// Empty (not an error) when `path` doesn't exist or isn't a YAML object —
/// `load_config`'s cascade already treats "file absent" as "this layer
/// contributes nothing," and `cli::config`'s display wants the same
/// leniency. Exposed for that display to read a layer's raw contents.
pub fn read_yaml_if_exists(path: &Path) -> Map<String, Value> {
    let Ok(contents) = std::fs::read_to_string(path) else {
        return Map::new();
    };
    match serde_yaml::from_str::<Value>(&contents) {
        Ok(Value::Object(map)) => map,
        _ => Map::new(),
    }
}

fn parse_env_value(config_key: &str, value: &str) -> Value {
    if matches!(
        config_key,
        "rate_limit" | "timeout_ms" | "cache_size" | "retry_attempts" | "port"
    ) && let Ok(number) = value.parse::<u64>()
    {
        return Value::Number(number.into());
    }
    Value::String(value.to_string())
}

/// Every `OKF_MCP_*` env var actually set in this process, keyed by the
/// `Config` field it maps to. Exposed for `cli::config`'s layered display,
/// which needs exactly this — "which env vars are actually set" — not
/// just the fully-merged/defaulted result `load_config` returns.
pub fn env_overrides() -> Map<String, Value> {
    let mut overrides = Map::new();
    for (config_key, env_suffix) in [
        ("url", "URL"),
        ("firecrawl_base_url", "FIRECRAWL_BASE_URL"),
        ("auth_method", "AUTH_METHOD"),
        ("api_version", "API_VERSION"),
        ("log_level", "LOG_LEVEL"),
        ("transport", "TRANSPORT"),
        ("host", "HOST"),
        ("cors_allow", "CORS_ALLOW"),
        ("rate_limit", "RATE_LIMIT"),
        ("timeout_ms", "TIMEOUT_MS"),
        ("cache_size", "CACHE_SIZE"),
        ("retry_attempts", "RETRY_ATTEMPTS"),
        ("port", "PORT"),
    ] {
        if let Ok(value) = std::env::var(format!("{ENV_PREFIX}_{env_suffix}")) {
            overrides.insert(config_key.to_string(), parse_env_value(config_key, &value));
        }
    }
    overrides
}

/// Resolves configuration through the strict, stop-at-first-match cascade
/// (REQ-2.2): CLI flags -> env vars -> local file
/// (`./okf-mcp.config.yml`) -> home file
/// (`~/.okf-mcp/config.yml`) -> system file
/// (`/etc/okf-mcp/config.yml`) -> install-dir file -> built-in
/// defaults (applied by `Config`'s own `#[serde(default = ...)]` fields).
pub fn load_config(cli_flags: Map<String, Value>) -> Result<Config, McpifyError> {
    let install_dir = std::env::current_exe()
        .ok()
        .and_then(|exe| exe.parent().map(Path::to_path_buf))
        .unwrap_or_else(|| PathBuf::from("."));

    let layers = [
        cli_flags,
        env_overrides(),
        read_yaml_if_exists(&PathBuf::from(LOCAL_CONFIG_FILE)),
        read_yaml_if_exists(&home_dir().join(CONFIG_DIR_NAME).join("config.yml")),
        read_yaml_if_exists(&PathBuf::from("/etc/okf-mcp/config.yml")),
        read_yaml_if_exists(&install_dir.join("config.yml")),
    ];

    // Lowest-priority layer merged first, each higher-priority layer merged
    // on top — `cli_flags` (index 0 above, applied last here) always wins,
    // matching the cascade's stop-at-first-match ordering.
    let mut merged = Map::new();
    for layer in layers.into_iter().rev() {
        merged.extend(layer);
    }

    serde_json::from_value(Value::Object(merged))
        .map_err(|err| McpifyError::Configuration(format!("invalid configuration: {err}")))
}

#[cfg(test)]
mod tests {
    use super::super::config_schema::AuthMethod;
    use super::*;
    use serde_json::json;

    fn base_flags() -> Map<String, Value> {
        json!({ "url": "https://api.example.com", "auth_method": "pat" })
            .as_object()
            .unwrap()
            .clone()
    }

    #[test]
    fn applies_built_in_defaults_when_nothing_else_is_set() {
        let config = load_config(base_flags()).unwrap();
        assert_eq!(config.log_level, "info");
        assert_eq!(config.rate_limit, 100);
        assert_eq!(config.port, 3000);
    }

    #[test]
    fn cli_flags_win_over_everything_else() {
        let mut flags = base_flags();
        flags.insert("log_level".to_string(), json!("debug"));
        let config = load_config(flags).unwrap();
        assert_eq!(config.log_level, "debug");
    }

    /// `url`/`auth_method` used to be required — they're both defaulted now
    /// (`url` to empty, `auth_method` to its only variant) so a fresh
    /// `okf-mcp ingest` run isn't blocked on configuring fields it never
    /// reads. Every `Config` field is defaultable, so an entirely empty
    /// cascade now loads successfully instead of erroring.
    #[test]
    fn an_entirely_empty_cascade_loads_successfully_with_defaults() {
        // Serialized with `credential_storage`'s HOME-mutating tests —
        // see that lock's doc comment for why this matters.
        let _guard = crate::core::credential_storage::HOME_ENV_TEST_LOCK
            .lock()
            .unwrap_or_else(|e| e.into_inner());
        let temp_dir = tempfile::tempdir().unwrap();
        let prev_home = std::env::var_os("HOME");
        unsafe {
            std::env::set_var("HOME", temp_dir.path());
        }
        let config = load_config(Map::new());
        if let Some(prev) = prev_home {
            unsafe {
                std::env::set_var("HOME", prev);
            }
        } else {
            unsafe {
                std::env::remove_var("HOME");
            }
        }
        let config = config.unwrap();
        assert_eq!(config.url, "");
        assert_eq!(config.firecrawl_base_url, "https://api.firecrawl.dev");
        assert_eq!(config.auth_method, AuthMethod::Pat);
    }

    #[test]
    fn read_yaml_if_exists_parses_a_valid_yaml_object() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("config.yml");
        std::fs::write(&path, "log_level: debug\n").unwrap();
        let map = read_yaml_if_exists(&path);
        assert_eq!(map.get("log_level"), Some(&json!("debug")));
    }

    #[test]
    fn read_yaml_if_exists_ignores_non_object_yaml() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("config.yml");
        std::fs::write(&path, "- just\n- a\n- list\n").unwrap();
        assert!(read_yaml_if_exists(&path).is_empty());
    }

    #[test]
    fn numeric_environment_overrides_are_typed_before_deserialization() {
        assert_eq!(parse_env_value("port", "33017"), json!(33017));
        assert_eq!(parse_env_value("timeout_ms", "2500"), json!(2500));
        assert_eq!(
            parse_env_value("url", "https://api.example"),
            json!("https://api.example")
        );
        assert_eq!(
            parse_env_value("port", "not-a-number"),
            json!("not-a-number")
        );
    }
}
