// OKF MCP server — generated by mcpify. Do not hand-edit.

use std::collections::HashMap;
use std::fs;
use std::path::PathBuf;

use aes_gcm::aead::{Aead, AeadCore, KeyInit, OsRng};
use aes_gcm::{Aes256Gcm, Key, Nonce};
use keyring::Entry;
use sha2::{Digest, Sha256};

const SERVICE_NAME: &str = "okf-mcp";

/// Resolves the user's home directory cross-platform: `HOME` (Unix/macOS),
/// falling back to `USERPROFILE` (Windows), falling back to the current
/// directory if neither is set — without this fallback, Windows deployments
/// silently resolve config/credential paths to `.` (cwd) instead of erroring
/// or using the user's actual profile directory.
pub fn resolve_home_dir() -> PathBuf {
    std::env::var_os("HOME")
        .or_else(|| std::env::var_os("USERPROFILE"))
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("."))
}

fn config_dir() -> PathBuf {
    resolve_home_dir().join(".okf-mcp")
}

fn fallback_file() -> PathBuf {
    config_dir().join("credentials.enc")
}

/// Derived from a machine/user-specific value so the encrypted fallback
/// file isn't portable to another machine by design, mirroring the OS
/// keychain's own implicit scoping — REQ-2.3.5. AES-256-GCM (authenticated
/// encryption) rather than `targets::typescript`'s AES-256-CBC: an
/// equally-simple choice available in this crate's toolchain that also
/// detects tampering, which CBC alone does not.
fn encryption_key() -> [u8; 32] {
    let home = resolve_home_dir();
    let mut hasher = Sha256::new();
    hasher.update(home.to_string_lossy().as_bytes());
    hasher.update(SERVICE_NAME.as_bytes());
    hasher.finalize().into()
}

fn to_hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

fn from_hex(input: &str) -> anyhow::Result<Vec<u8>> {
    if !input.len().is_multiple_of(2) {
        anyhow::bail!("odd-length hex string");
    }
    (0..input.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&input[i..i + 2], 16).map_err(anyhow::Error::from))
        .collect()
}

fn read_store() -> HashMap<String, String> {
    fs::read_to_string(fallback_file())
        .ok()
        .and_then(|contents| serde_json::from_str(&contents).ok())
        .unwrap_or_default()
}

fn write_store(store: &HashMap<String, String>) -> anyhow::Result<()> {
    let dir = config_dir();
    fs::create_dir_all(&dir)?;
    let contents = serde_json::to_string(store)?;
    fs::write(fallback_file(), contents)?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        fs::set_permissions(&dir, fs::Permissions::from_mode(0o700))?;
        fs::set_permissions(fallback_file(), fs::Permissions::from_mode(0o600))?;
    }

    Ok(())
}

fn save_to_file(account: &str, value: &str) -> anyhow::Result<()> {
    let key_bytes = encryption_key();
    let key: &Key<Aes256Gcm> = (&key_bytes).into();
    let cipher = Aes256Gcm::new(key);
    let nonce = Aes256Gcm::generate_nonce(&mut OsRng);
    let ciphertext = cipher
        .encrypt(&nonce, value.as_bytes())
        .map_err(|_| anyhow::anyhow!("failed to encrypt credential"))?;

    let mut store = read_store();
    store.insert(
        account.to_string(),
        format!("{}:{}", to_hex(&nonce), to_hex(&ciphertext)),
    );
    write_store(&store)
}

fn load_from_file(account: &str) -> anyhow::Result<Option<String>> {
    let store = read_store();
    let Some(raw) = store.get(account) else {
        return Ok(None);
    };
    let (nonce_hex, ciphertext_hex) = raw
        .split_once(':')
        .ok_or_else(|| anyhow::anyhow!("corrupt credential entry for '{account}'"))?;

    let key_bytes = encryption_key();
    let key: &Key<Aes256Gcm> = (&key_bytes).into();
    let cipher = Aes256Gcm::new(key);
    let nonce_bytes = from_hex(nonce_hex)?;
    let nonce = Nonce::from_slice(&nonce_bytes);
    let ciphertext = from_hex(ciphertext_hex)?;
    let plaintext = cipher
        .decrypt(nonce, ciphertext.as_ref())
        .map_err(|_| anyhow::anyhow!("failed to decrypt credential for '{account}'"))?;

    Ok(Some(String::from_utf8(plaintext)?))
}

fn delete_from_file(account: &str) -> anyhow::Result<()> {
    let mut store = read_store();
    if store.remove(account).is_some() {
        write_store(&store)?;
    }
    Ok(())
}

/// Persists a credential to the OS-native keychain when available (macOS
/// Keychain, Windows Credential Manager, Linux Secret Service via the
/// `keyring` crate), falling back to an AES-256-GCM-encrypted local file
/// when the platform backend is unavailable (e.g. no D-Bus secret-service
/// daemon running, common in minimal containers) — REQ-2.3.5.
pub fn save_credential(account: &str, value: &str) -> anyhow::Result<()> {
    match Entry::new(SERVICE_NAME, account).and_then(|entry| entry.set_password(value)) {
        Ok(()) => Ok(()),
        Err(err) => {
            tracing::warn!(error = %err, "OS keychain unavailable; falling back to encrypted file storage");
            save_to_file(account, value)
        }
    }
}

pub fn load_credential(account: &str) -> anyhow::Result<Option<String>> {
    match Entry::new(SERVICE_NAME, account).and_then(|entry| entry.get_password()) {
        Ok(password) => Ok(Some(password)),
        // A clean "no entry" from the keychain doesn't rule out a
        // credential that only ever landed in the encrypted-file fallback
        // (e.g. saved while the keychain backend was unavailable) — always
        // consult the file before reporting nothing found, whether the
        // keychain returned `NoEntry` or a harder error.
        Err(_) => load_from_file(account),
    }
}

/// Whether `account` has a saved credential — checks the OS keychain
/// first, falling back to the encrypted-file store, mirroring
/// `load_credential`'s own lookup order. Note: like `load_credential`,
/// this still materializes the plaintext transiently inside this
/// function's call to it; the guarantee it provides is that the plaintext
/// never escapes to the caller, not that it's never decrypted at all.
pub fn credential_exists(account: &str) -> anyhow::Result<bool> {
    Ok(load_credential(account)?.is_some())
}

pub fn delete_credential(account: &str) -> anyhow::Result<()> {
    match Entry::new(SERVICE_NAME, account).and_then(|entry| entry.delete_credential()) {
        Ok(()) | Err(keyring::Error::NoEntry) => Ok(()),
        Err(_) => delete_from_file(account),
    }
}

/// Guards every test (in this file and in `config_manager`'s) that mutates
/// the process-global `HOME` env var. `encryption_key()` derives its key
/// from `resolve_home_dir()`, so without this lock, `cargo test`'s default
/// parallel execution can interleave two tests' `HOME` changes — e.g.
/// another test restoring `HOME` in the gap between this file's
/// save-then-load — and a save/load pair ends up using two different
/// derived keys, breaking decryption non-deterministically.
#[cfg(test)]
pub(crate) static HOME_ENV_TEST_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn hex_round_trips_arbitrary_bytes() {
        let bytes = [0u8, 1, 15, 16, 255, 42];
        assert_eq!(from_hex(&to_hex(&bytes)).unwrap(), bytes);
    }

    #[test]
    fn from_hex_rejects_an_odd_length_string() {
        assert!(from_hex("abc").is_err());
    }

    #[test]
    fn file_fallback_round_trips_a_credential() {
        // Exercises the encrypted-file path directly rather than through
        // `save_credential`/`load_credential`, since the OS keychain (the
        // primary path) may or may not be available in the test
        // environment and this test should be deterministic either way.
        let _guard = HOME_ENV_TEST_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        let dir = tempfile::tempdir().unwrap();
        let prev_home = std::env::var_os("HOME");
        // SAFETY: test-only env mutation, serialized by HOME_ENV_TEST_LOCK
        // across every test (in this file and config_manager's) that
        // touches HOME.
        unsafe {
            std::env::set_var("HOME", dir.path());
        }

        save_to_file("test-account", "s3cr3t").unwrap();
        let loaded = load_from_file("test-account").unwrap();
        assert_eq!(loaded.as_deref(), Some("s3cr3t"));

        delete_from_file("test-account").unwrap();
        assert_eq!(load_from_file("test-account").unwrap(), None);

        // SAFETY: same guard as above.
        unsafe {
            match prev_home {
                Some(prev) => std::env::set_var("HOME", prev),
                None => std::env::remove_var("HOME"),
            }
        }
    }

    #[test]
    fn credential_exists_reflects_save_and_delete() {
        let _guard = HOME_ENV_TEST_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        let dir = tempfile::tempdir().unwrap();
        let prev_home = std::env::var_os("HOME");
        // SAFETY: test-only env mutation, serialized by HOME_ENV_TEST_LOCK.
        unsafe {
            std::env::set_var("HOME", dir.path());
        }

        let account = "credential-exists-test-account";
        assert!(!credential_exists(account).unwrap());

        save_credential(account, "s3cr3t").unwrap();
        assert!(credential_exists(account).unwrap());

        delete_credential(account).unwrap();
        assert!(!credential_exists(account).unwrap());

        // SAFETY: same guard as above.
        unsafe {
            match prev_home {
                Some(prev) => std::env::set_var("HOME", prev),
                None => std::env::remove_var("HOME"),
            }
        }
    }
}
