// OKF MCP server — generated by mcpify. Do not hand-edit.
//
// Terminal Client entry point (`search`/`get`/`call`/`test-connection`/
// `config`/`version` run as direct CLI subcommands) and Harness Server
// entry point (`start`/`http` boot the persistent MCP server loop) in one
// binary — Rust's single `[[bin]]`-per-binary-target model doesn't split
// these into two compiled entry points the way `targets::typescript`'s
// index.ts/cli.ts pair does.

mod cli;

use std::sync::Arc;

#[cfg(feature = "profiling")]
#[global_allocator]
static ALLOC: dhat::Alloc = dhat::Alloc;

use clap::{Parser, Subcommand};
use tokio::sync::Mutex;

use okf_mcp::auth::auth_manager::AuthManager;
use okf_mcp::core::component_registry::ComponentRegistry;
use okf_mcp::core::config_manager::load_config;
use okf_mcp::core::config_schema::Transport;
use okf_mcp::core::health_check_manager::HealthCheckManager;
use okf_mcp::core::logger::init_logging;
use okf_mcp::core::mcp_server::{OkfServer, connect_stdio};
use okf_mcp::core::otel;
use okf_mcp::core::shutdown_handler::{install_shutdown_handlers, on_shutdown};
use okf_mcp::http::server::start_http_server;
use okf_mcp::http::types::HttpServerConfig;

#[derive(Parser)]
#[command(
    name = "okf-mcp",
    about = "OKF (Open Knowledge Format) pipeline",
    version
)]
struct Cli {
    /// Vault name (from the registry) or path — overrides the CWD `.okf/`
    /// walk-up and the registry default. Global: works on every subcommand.
    #[arg(long, global = true)]
    vault: Option<String>,
    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand)]
enum Command {
    /// Configure the Firecrawl API key and an LLM provider key
    Setup,
    /// List or clear stored credentials (API keys saved via `setup`) —
    /// the symmetric "undo" for `setup`
    #[command(subcommand)]
    Credentials(CredentialsCommand),
    /// Fetch a URL (via Firecrawl) or read a local file and add it to the
    /// vault's raw sources
    Ingest {
        source: String,
        /// Repeatable: --tag github --tag repository --tag mcpify
        #[arg(long)]
        tag: Vec<String>,
    },
    /// Compile newly-ingested raw sources into wiki concept pages
    Compile {
        /// "<provider>/<model_name>", e.g. "anthropic/claude-3-5-sonnet" — for local
        /// Ollama models, an 8B-9B instruct model (e.g. "ollama/llama3.1:8b") is the
        /// best local speed/quality balance for this command; smaller models are
        /// unreliable at compile's structured JSON output, and 12B+ can be very slow
        /// on constrained hardware; run `okf-mcp models <provider>` to see what's
        /// actually available
        #[arg(long)]
        model: Option<String>,
        /// Show which sources would be compiled, without calling the LLM
        #[arg(long)]
        diff: bool,
        /// Repair lint issues after compiling: mechanically (missing `.md`
        /// extensions on `sources:` entries) and, for broken links, via the
        /// LLM — synthesizing a concept page for a missing link target,
        /// grounded only in the raw sources the referencing pages already
        /// cite. LLM-synthesized changes prompt for commit confirmation
        /// unless --yes is also passed.
        #[arg(long)]
        fix: bool,
        /// Skip the commit confirmation prompt for --fix's LLM-synthesized
        /// changes and commit them automatically
        #[arg(long, short = 'y')]
        yes: bool,
        /// Compile this many sources concurrently (default 1, sequential).
        /// Raising it trades some cross-linking completeness within a
        /// concurrent wave for throughput — see `compiler::driver::compile`'s
        /// doc comment for the exact trade-off; the post-compile lint pass
        /// (and --fix) remain the safety net either way
        #[arg(long, default_value_t = 1)]
        concurrency: usize,
    },
    /// Recompile the wiki from all active raw sources
    Rebuild {
        /// "<provider>/<model_name>" — see `compile --help` for model-size guidance
        #[arg(long)]
        model: Option<String>,
        /// Recompile every active source, not just unprocessed ones
        #[arg(long)]
        force: bool,
        /// Same as `compile --fix` — see its help for details
        #[arg(long)]
        fix: bool,
        /// Same as `compile --yes` — see its help for details
        #[arg(long, short = 'y')]
        yes: bool,
        /// Same as `compile --concurrency` — see its help for details
        #[arg(long, default_value_t = 1)]
        concurrency: usize,
    },
    /// List a provider's available models (e.g. before picking `--model`)
    Models {
        /// anthropic, openai, groq, gemini, openrouter, deepseek, xai,
        /// together, ollama-cloud, moonshot, ollama, or custom
        provider: String,
    },
    /// Check wikilinks, frontmatter, and source provenance in the wiki
    Lint {
        #[arg(long)]
        strict: bool,
        #[arg(long)]
        json: bool,
        /// Mechanically repair auto-fixable issues (currently: missing
        /// `.md` extensions on `sources:` entries) before reporting
        #[arg(long)]
        fix: bool,
    },
    /// Rebuild the local text and vector index used by search
    Reindex {
        /// Also (re)compute dense-vector embeddings, not just the text index
        #[arg(long)]
        embeddings: bool,
    },
    /// Search ingested raw sources and compiled wiki concepts
    Search {
        query: String,
        #[arg(short = 'l', long, default_value_t = 5)]
        limit: usize,
        #[arg(long)]
        json: bool,
        /// Search every registered vault, not just the resolved one
        #[arg(long)]
        all_vaults: bool,
    },
    /// Remove a source from the vault (soft by default; --purge hard-deletes)
    Delete {
        source: String,
        #[arg(long)]
        purge: bool,
    },
    /// Ingest, compile, lint, and commit a source as one step
    Run {
        source: String,
        /// Repeatable: --tag github --tag repository --tag mcpify
        #[arg(long)]
        tag: Vec<String>,
        /// "<provider>/<model_name>" — see `compile --help` for model-size guidance
        #[arg(long)]
        model: Option<String>,
        /// Same as `compile --fix` — see its help for details
        #[arg(long)]
        fix: bool,
        /// Same as `compile --yes` — see its help for details
        #[arg(long, short = 'y')]
        yes: bool,
    },
    /// Manage vaults / knowledge bases (~/.config/okf/vaults.toml) — alias:
    /// `kb`. `vault` and `kb` are the same commands under two names: `vault`
    /// for Obsidian-oriented workflows, `kb` for OKF-oriented ones.
    #[command(subcommand, alias = "kb")]
    Vault(VaultCommand),
    /// Start the MCP server over stdio (for agent hosts)
    Start,
    /// Start the MCP server over HTTP (for agent hosts)
    Http {
        #[arg(long)]
        host: Option<String>,
        #[arg(long)]
        port: Option<u16>,
        #[arg(long)]
        cors_allow: Option<String>,
    },
    /// Verify the configured Firecrawl API key is reachable
    TestConnection,
    /// Print the resolved configuration (secrets redacted)
    Config,
    /// Print the installed version
    Version,
}

#[derive(Subcommand)]
enum CredentialsCommand {
    /// List every account this codebase could have saved a credential
    /// under, and whether one is actually saved — never the credential's
    /// value
    List,
    /// Delete one or more saved credentials
    Clear {
        /// Provider name (e.g. "anthropic"; or "firecrawl" for the
        /// Firecrawl credential) — clears just that one credential
        #[arg(long)]
        provider: Option<String>,
        /// Clear every known credential
        #[arg(long)]
        all: bool,
        /// Skip the confirmation prompt
        #[arg(long, short = 'y')]
        yes: bool,
    },
}

#[derive(Subcommand)]
enum VaultCommand {
    /// List registered vaults
    List,
    /// Register an existing vault directory
    Add {
        path: String,
        #[arg(long)]
        name: String,
        #[arg(long)]
        description: Option<String>,
    },
    /// Scaffold a brand-new vault directory (.okf/, wiki/concepts/, raw/) and register it
    Create {
        path: String,
        #[arg(long)]
        name: String,
        #[arg(long)]
        description: Option<String>,
    },
    /// Remove a vault from the registry (~/.config/okf/vaults.toml)
    #[command(alias = "rm")]
    Remove { name: String },
    /// Unregister a vault AND permanently delete its directory tree (destructive — requires --force)
    Delete {
        name: String,
        #[arg(long)]
        force: bool,
    },
    /// Set the default vault
    Default { name: String },
}

/// Bootstrap order (architecture.md's Runtime Target Architecture): config
/// -> logger -> tracing -> registry -> shutdown-handler -> db -> auth ->
/// McpServer -> pick transport -> health checks. Mirrors
/// `targets::typescript`'s `index.ts` `main()`.
async fn run_harness_server() -> anyhow::Result<()> {
    let config = load_config(serde_json::Map::new())?;

    let (otel_layer, otel_provider) = match otel::build_layer("okf-mcp") {
        Ok((layer, provider)) => (Some(layer), Some(provider)),
        Err(_) => (None, None),
    };
    init_logging(otel_layer);
    install_shutdown_handlers();
    if let Some(provider) = otel_provider {
        on_shutdown(Box::new(move || {
            let provider = provider.clone();
            Box::pin(async move { otel::shutdown_tracing(provider) })
        }));
    }

    let registry = Arc::new(Mutex::new(ComponentRegistry::new()));
    // No components are registered here: unlike the old single compiled-in
    // catalog database, there's no one server-level resource whose health
    // is meaningful to report up front — each tool call resolves and
    // validates its own vault per-call, surfacing any problem through that
    // call's own error response. `/healthz` reports `Healthy` with zero
    // registered components (see `ComponentRegistry::overall_status`),
    // which correctly reflects "the process itself is up."
    let health_checks = HealthCheckManager::new(registry.clone());
    let health_checks = Arc::new(health_checks);
    let health_check_handle = health_checks.start();
    on_shutdown(Box::new(move || {
        health_check_handle.abort();
        Box::pin(async move {})
    }));

    let auth_manager = Arc::new(Mutex::new(AuthManager::new(config.auth_method)));

    if config.transport == Transport::Http {
        let http_config = HttpServerConfig {
            host: config.host.clone(),
            port: config.port,
            cors_allow: config.cors_allow.clone(),
        };
        let (header_location, header_name) =
            okf_mcp::auth::auth_manager::header_location_for(config.auth_method);
        let factory_config = config.clone();
        start_http_server(
            move || Ok(OkfServer::new(factory_config.clone(), auth_manager.clone())),
            &http_config,
            registry,
            header_location,
            header_name.to_string(),
        )
        .await?;
    } else {
        connect_stdio(OkfServer::new(config, auth_manager)).await?;
    }

    Ok(())
}

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    // Must run before anything builds a TLS client (our own reqwest client,
    // or opentelemetry-otlp's HTTP exporter): rustls 0.23 requires a
    // process-wide default crypto provider, and nothing installs one
    // automatically once more than one provider feature is in the
    // dependency tree.
    rustls::crypto::aws_lc_rs::default_provider()
        .install_default()
        .expect("failed to install rustls crypto provider");

    let cli = Cli::parse();
    let vault = cli.vault.as_deref();

    #[cfg(feature = "profiling")]
    let _dhat_profiler = dhat::Profiler::new_heap();

    let result = match cli.command {
        Command::Setup => cli::setup::run().await,
        Command::Credentials(CredentialsCommand::List) => cli::credentials::run_list(),
        Command::Credentials(CredentialsCommand::Clear { provider, all, yes }) => {
            cli::credentials::run_clear(provider.as_deref(), all, yes).await
        }
        Command::Ingest { source, tag } => cli::ingest::run(&source, &tag, vault).await,
        Command::Compile {
            model,
            diff,
            fix,
            yes,
            concurrency,
        } => cli::compile::run(model.as_deref(), diff, fix, yes, concurrency, vault).await,
        Command::Rebuild {
            model,
            force,
            fix,
            yes,
            concurrency,
        } => cli::rebuild::run(model.as_deref(), force, fix, yes, concurrency, vault).await,
        Command::Models { provider } => cli::models::run(&provider, vault).await,
        Command::Lint { strict, json, fix } => cli::lint::run(strict, json, fix, vault),
        Command::Reindex { embeddings } => cli::reindex::run(embeddings, vault),
        Command::Search {
            query,
            limit,
            json,
            all_vaults,
        } => cli::search::run(&query, limit, json, all_vaults, vault),
        Command::Delete { source, purge } => cli::delete::run(&source, purge, vault),
        Command::Run {
            source,
            tag,
            model,
            fix,
            yes,
        } => cli::run::run(&source, &tag, model.as_deref(), fix, yes, vault).await,
        Command::Vault(VaultCommand::List) => cli::vault::list(),
        Command::Vault(VaultCommand::Add {
            path,
            name,
            description,
        }) => cli::vault::add(&path, &name, description.as_deref()),
        Command::Vault(VaultCommand::Create {
            path,
            name,
            description,
        }) => cli::vault::create(&path, &name, description.as_deref()),
        Command::Vault(VaultCommand::Remove { name }) => cli::vault::remove(&name),
        Command::Vault(VaultCommand::Delete { name, force }) => cli::vault::delete(&name, force),
        Command::Vault(VaultCommand::Default { name }) => cli::vault::default(&name),
        Command::Start => {
            // SAFETY: single-threaded at this point, before `#[tokio::main]`
            // spawns any concurrent work that would also touch env vars.
            unsafe {
                std::env::set_var("OKF_MCP_TRANSPORT", "stdio");
            }
            run_harness_server().await
        }
        Command::Http {
            host,
            port,
            cors_allow,
        } => {
            // SAFETY: single-threaded at this point, before `#[tokio::main]`
            // spawns any concurrent work that would also touch env vars.
            unsafe {
                std::env::set_var("OKF_MCP_TRANSPORT", "http");
                if let Some(host) = &host {
                    std::env::set_var("OKF_MCP_HOST", host);
                }
                if let Some(port) = port {
                    std::env::set_var("OKF_MCP_PORT", port.to_string());
                }
                if let Some(cors_allow) = &cors_allow {
                    std::env::set_var("OKF_MCP_CORS_ALLOW", cors_allow);
                }
            }
            run_harness_server().await
        }
        Command::TestConnection => cli::test_connection::run().await,
        Command::Config => cli::config::run(vault),
        Command::Version => cli::version::run(),
    };

    if let Err(err) = result {
        eprintln!("{err}");
        std::process::exit(1);
    }
    Ok(())
}
